# Generated by Django 4.0.3 on 2022-03-16 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=240)),
                ('marca', models.CharField(max_length=60)),
                ('modelo', models.CharField(max_length=60)),
                ('numero', models.CharField(max_length=60)),
                ('nome', models.CharField(max_length=60)),
                ('state', models.IntegerField(default=0)),
                ('setor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setor.setor')),
            ],
        ),
    ]
