# Generated by Django 3.2.6 on 2022-02-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('conteudo', models.TextField()),
                ('hasPage', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner')),
                ('data_pub', models.DateField(auto_now_add=True)),
                ('state', models.IntegerField(default=0)),
                ('ordem', models.IntegerField(null=True)),
                ('link_externo', models.CharField(max_length=255)),
            ],
        ),
    ]
