# Generated by Django 4.0.3 on 2022-03-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='link_externo',
            field=models.URLField(max_length=255),
        ),
    ]
