# Generated by Django 3.2.6 on 2021-08-20 13:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=60, unique=True)),
                ('adm_nome', models.CharField(max_length=60)),
                ('senha_hash', models.CharField(max_length=128)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_publisher', models.BooleanField(default=False)),
            ],
        ),
    ]
