# Generated by Django 4.0.3 on 2022-03-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_nome', models.CharField(max_length=60)),
                ('state', models.IntegerField(default=0)),
                ('rank', models.IntegerField(null=True)),
            ],
        ),
    ]
