# Generated by Django 3.2.6 on 2021-08-20 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tabela', models.CharField(max_length=60)),
                ('createdon', models.DateField(auto_now_add=True)),
                ('ip', models.CharField(max_length=60)),
                ('action', models.CharField(max_length=240)),
                ('hostname', models.CharField(max_length=60)),
                ('usuario', models.CharField(max_length=60)),
                ('id_tab', models.IntegerField()),
            ],
        ),
    ]
