# Generated by Django 3.2.6 on 2022-02-03 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('dia_nasc', models.IntegerField()),
                ('mes_nasc', models.CharField(max_length=20)),
                ('state', models.BooleanField()),
                ('setor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setor.setor')),
            ],
        ),
    ]
