# Generated by Django 4.0.3 on 2022-03-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabela', models.CharField(max_length=60)),
                ('createdon', models.DateField(auto_now_add=True)),
                ('ip', models.CharField(max_length=60)),
                ('action', models.CharField(max_length=240)),
                ('hostname', models.CharField(max_length=60)),
                ('usuario', models.CharField(max_length=60)),
                ('id_tab', models.IntegerField()),
            ],
        ),
    ]
