# Generated by Django 3.2.6 on 2021-08-20 13:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=60)),
                ('conteudo', models.TextField()),
                ('hasPage', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner')),
                ('data_pub', models.DateField(auto_now_add=True)),
                ('state', models.IntegerField(default=0)),
            ],
        ),
    ]
